### ISSUE TITLE
[Bug?] Patch is applied before file creation

### ISSUE THREAD

**Issue by ineanto** [itzg/mc-image-helper#402] opened 2024-02-18 21:14 UTC
Hi, first of all, thank you for your incredible work . The issue that I'm encountering is related to the fact that I'd like to patch the "/data/config/paper-global.yml" file before the server starts. I'm using ```docker-java``` to create the environment and pass the envars to the container. However, this file is created AFTER the server is started for the first time. Would it be possible for ```mc-image-helper``` to just start the server once, and then automatically restart while patching files?

Edit: Tried to fix it by coping the default "paper-global.yml" file from a completely clean server and then patching it. It kinda works, but when the file's version inevitably gets updated, this will break... 

 Thank you!

**Comment by itzg** [comment] 2024-02-18 22:24
Fair request but very difficult to implement. It's a duplicate of https://github.com/itzg/docker-minecraft-server/issues/2522 so I'll close this one.

**Closed** 2024-02-18 22:25 UTC

**Comment by ineanto** [comment] 2024-02-18 23:18
Whoops, sorry for not checking the other repositories! I'll try your provided solution, thank you!

**Comment by itzg** [comment] 2024-02-18 23:33
No problem at all. The patching happens with the helper, so it was a logical place to log the issue.
